### ISSUE TITLE
More cli-friendly flags

### ISSUE THREAD

**Issue by jdanbrown** [duckworthd/configurati#1]
Instead of:

```
$ python application.py '--int_variable' '0' '--list_variable[1].key' '"new value"'
```

I would like to write:

```
$ python application.py --int-variable 0 --list-variable[1].key '"new value"'
```

Shell escaping is very unlikely to barf on `--list-variable[1].key`, so I think the only thing required is this feature request:
- Transform incoming flags like `flag.replace('-', '_')` so that `--int-variable` and `--int_variable` are treated the same

It would also be nice to avoid the double quoting in `'"new value"'`, but if you want each cli option to determine the type of its python value, I don't see a great way of doing that...

**Comment by duckworthd** [comment]
Done,

``` bash
$ python application.py --int_variable 0
$ python application.py --list-variable.1.key '"new value"'
```
